site_name: MIPS - ASSEMBLY
site_url: https://example.com
nav:
  - Visão geral - MIPS: index.md
  - System Call: syscall.md
  - Instruções - Assembly: instrucoes.md
  - Exemplos - Lista: examples.md
  
theme: material
